# Generated by Django 5.1.2 on 2024-10-22 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_project_is_completed_project_project_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="project",
            name="technology",
        ),
    ]
