# Generated by Django 5.1.2 on 2024-10-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_remove_project_is_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
