# Generated by Django 5.1.2 on 2024-10-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_rename_project_url_project_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FilePathField(path="/portfolio/templates/portfolio/img"),
        ),
    ]
