# Generated by Django 5.1.2 on 2024-10-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_project_progress_alter_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("education", "Обучение"), ("work", "Место работы")],
                        default="education",
                        max_length=10,
                    ),
                ),
                ("institution", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("technologies", models.TextField()),
                ("achievements", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
