# Generated by Django 5.2.6 on 2025-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_contactinfo_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('work', 'Рабочие'), ('university', 'Вузовские'), ('personal', 'Личные/пэт')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
