# Generated by Django 5.2.6 on 2025-12-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_project_image_project_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
